# -*- coding: utf-8 -*-
"""Does anime length affect its rating?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192fuGvbxBVPm80QNn5BWlnyhc-ZOauuO
"""

import pandas as pd

data = {
  'Title': [
    'Classroom of the Elite',
    'Death Note',
    'Code Geass',
    'Eminence in Shadow',
    'Solo Leveling',
    'Naruto (Classic + Shippuden)',
    'Jujutsu Kaisen (S1–S2)',
    'Darling in the FRANXX',
    'Demon Slayer',
    'Attack on Titan (first 3 seasons)'
  ],

  'Genres': [
    'Psychological thriller',
    'Psychological thriller',
    'Action,Drama,Sci-Fi',
    'Action-comedy, dark fantasy isekai',
    'Action-fantasy',
    'Action-adventure and fantasy',
    'Dark fantasy, supernatural adventure',
    'Mecha, sci-fi, romantic drama',
    'Dark fantasy, action-adventure',
    'Dark fantasy, post-apocalyptic action-thriller'
  ],

  'Rating': [
    9.36, 9.4, 9.6, 9.45, 9.6, 9.35, 9.35, 9.6, 9.5, 9.53
  ],

  'Episodes': [
    '12, 13, 13',
    '37',
    '25, 25',
    '20, 12',
    '12, 13',
    '220, 500',
    '24, 23',
    '24',
    '26, 11, 11, 8',
    '25, 12, 22'
  ],


  'Episode Length': [
    '24 min.', '23 min.', '24 min.', '24 min.', '24 min.',
    '24 min.', '24 min.', '24 min.', '24 min.', '24 min.'
  ],

  'Release Date': [
    'Summer 2017', 'Autumn 2006', 'Autumn 2006', 'Autumn 2022',
    'Spring 2024', 'Autumn 2002', 'Autumn 2020', 'Winter 2018',
    'Spring 2019', 'Spring 2013'
  ]
}

df = pd.DataFrame(data)


# -------------------------
# Convert "12, 13, 13" to total episodes (important for analysis)
# -------------------------

def count_total_eps(ep_string):
    nums = [int(x.strip()) for x in ep_string.split(',')]
    return sum(nums)

df["Total Episodes"] = df["Episodes"].apply(count_total_eps)


print(df)

df

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")  # cleaner look ig



#


plt.figure(figsize=(10,6))

sns.barplot(
    data=df.sort_values("Total Episodes", ascending=False),
    x="Total Episodes",
    y="Title",
    palette="viridis"
)

plt.title("Total Episodes per Anime")
plt.xlabel("Total Episodes")
plt.ylabel("Anime")

plt.tight_layout()
plt.show()




#


plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x="Total Episodes",
    y="Rating",
    s=150
)


sns.regplot(
    data=df,
    x="Total Episodes",
    y="Rating",
    scatter=False,
    color="red"
)

plt.title("Does Anime Length Affect Rating?")
plt.xlabel("Total Episodes")
plt.ylabel("Rating")

plt.tight_layout()
plt.show()


# correlation number
corr = df["Total Episodes"].corr(df["Rating"])
print(f"\nCorrelation between length and rating: {corr:.2f}")




#


plt.figure(figsize=(10,6))

sns.barplot(
    data=df.sort_values("Rating", ascending=False),
    x="Rating",
    y="Title",
    palette="magma"
)

plt.title("Anime Ranked by Rating")
plt.xlabel("Rating")
plt.ylabel("Anime")

plt.tight_layout()
plt.show()

